 <script src="<?=base_url('user/assets/js/vendor/jquery-3.6.0.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/slick.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/bootstrap.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/jquery.magnific-popup.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/jquery.counterup.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/imagesloaded.pkgd.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/isotope.pkgd.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/nice-select.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/jquery.datetimepicker.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/wow.min.js')?>"></script>
    <script src="<?=base_url('user/assets/js/main.js')?>"></script>